---
- name: Manage Windows Server
  hosts: windows
  tasks:

    - name: Ping the Windows host
      win_ping:

    - name: Create a directory
      win_file:
        path: C:\example_dir
        state: directory
   
    - name: Copy a file to the Windows host
      win_copy:
        src: ../roles/windows/files/test.txt
        dest: C:\example_dir
    
    - name: Ensure the Windows Feature IIS is installed
      win_feature:
        name: Web-Server
        state: present

    - name: Copy Notepad++ installer to the remote machine
      win_copy:
        src: ../roles/windows/files/npp.8.6.5.Installer.x64.exe
        dest: C:\temp\

    - name: Run Notepad++ installer
      win_package:
        path: C:\temp\npp.8.6.5.Installer.x64.exe
        state: present
        arguments: /S
      register: install_notepadpp_result

    - name: Remove the installer after installation
      win_file:
        path: C:\temp\npp.8.6.5.Installer.x64.exe
        state: absent
      when: install_notepadpp_result is succeeded

                                                                                                                                                                                                                                                                
